apiVersion: serving.knative.dev/v1
kind: Service
metadata:
 name: service2
spec:
 template:
  spec:
   serviceaccountName: <update default service account>
   containers:
   - image: image 
     name: myweb2
     ports:
        - name: http1
          containerPort: 80
