apiVersion: serving.knative.dev/v1
kind: Service
metadata:
 name: service1
spec:
 template:
  spec:
   serviceaccountName: <update default service account>
   containers:
   - image: image 
     name: myweb1
     ports:
        - name: http1
          containerPort: 80
