steps:
# Build the Image  
- name: 'gcr.io/cloud-builders/docker'
  dir: '03-cb-cd-private-gke/apps'
  args: [ 'build', '-t', 'europe-docker.pkg.dev/$PROJECT_ID/my-repository/nginx:v1.0', '.' ]

# Push the Image to Google Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  dir: '03-cb-cd-private-gke/apps'
  args: ['push', 'europe-docker.pkg.dev/$PROJECT_ID/my-repository/nginx:v1.0']

# Deploy the Image to Public GKE via Google  Cloud Deploy Pipeline
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: bash
  dir: '03-cb-cd-private-gke/apps'
  args:
  - '-c'
  - 'gcloud beta deploy releases create rel-$(date +%y%m%d-%s) --delivery-pipeline=cloud-deploy-pipeline-pri-gke --region=asia-south1  --images=image=europe-docker.pkg.dev/$PROJECT_ID/my-repository/nginx:v1.0'


options:
  logging: CLOUD_LOGGING_ONLY
  workerPool:
    'projects/$PROJECT_ID/locations/us-central1/workerPools/private-pool'
